export enum PageRouter {
  Index = 'index',
  Welcome = 'welcome',
  CreateRoom = 'create_room',
  JoinRoom = 'join_room',
  Detail = 'detail',
  Invite = 'invite_room',
  Launch = 'launch',
  IndexMobileWeb = 'index_mobile_web',
  JoinRoomMobileWeb = 'join_room_mobile_web',
  InviteMobileWeb = 'invite_room_mobile_web',
  Logout = 'logout',
  FlexHome = 'flex_home',
  RecordationSearchPage = 'recordation_search',
  QuickJoin = 'quick_join',
  Window = 'window',
}
