export enum SvgIconEnum {
  BACKWARD = 'backward',
  CALENDAR = 'calendar',
  COPY = 'copy',
  CLOSE = 'close',
  EDIT = 'edit',
  DOWN = 'down',
  FORWARD = 'forward',
  REPLAY = 'replay',
  ROOM_LABEL = 'room-label',
  SET = 'set',
  SETTINGS = 'settings',
  SHARE_CLOSE = 'share-close',
  TEXT = 'text',
  TOAST_INFO = 'toast-info',
  TOAST_SUCCESS = 'toast-success',
  TRIANGLE = 'triangle',
  TRIANGLE_SOLID_DOWN = 'triangle-solid-down',
  CLOCK = 'clock',
  FCR_DOWNLOADAPP = 'fcr_downloadapp',
  FCR_HOME_SEEKADVICCEFROM = 'fcr_home_seekadvicefrom',
  FCR_QUESTION = 'fcr_question',
  MORE = 'more',
  FCR_GEAR = 'fcr_gear',
  EMAIL = 'email',
  FACEBOOK_MESSENGER = 'facebook-messenger',
  SLACK = 'slack',
}
